micronaut:
  application:
    name: gcpPubsubEmulatorUi
  io:
    watch:
      paths: src/main
      restart: true

gcp:
  pubsub:
    emulator:
      ui:
        projects: ${GCP_PROJECT_IDS:company-dev,company-staging}
        emulator-host: http://${EMULATOR_HOST:`localhost:8681`}
