micronaut:
  application:
    name: gcpPubsubEmulatorUi
  io:
    watch:
      paths: src/main
      restart: true
  router:
    static-resources:
      default:
        enabled: true
        mapping: "/**"
        paths: "classpath:static"
  server:
    port: 8680
gcp:
  pubsub:
    emulator:
      ui:
        emulator-host: http://${EMULATOR_HOST:`localhost:8681`}
        projects: ${GCP_PROJECT_IDS:company-dev,company-staging}
